#!/usr/bin/env python

import sys

from rqt_openstf_teleop.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_openstf_teleop'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))